"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useState } from "react";

type Question = { id: string; label: string; type: "rating" | "text"; ratingScale: number | null; required: boolean };
type FeedbackData = { order: { orderNumber: string; fulfilment: string }; alreadySubmitted: boolean; googleReviewUrl: string | null; questions: Question[] };

function Header() { return <header className="utility-header"><a className="brand" href="/"><span className="pizza-mark"><span>62</span><i className="pizza-dot pizza-dot--one" /></span><span className="brand-copy"><strong>Pizza 62</strong><small>Hamilton, Ontario</small></span></a><a href="/">Back to menu ↗</a></header>; }

function initialFeedbackParams() {
  if (typeof window === "undefined") return { order: "", token: "" };
  const params = new URLSearchParams(window.location.search);
  return { order: params.get("order") ?? "", token: params.get("token") ?? "" };
}

export default function FeedbackApp() {
  const [initial] = useState(initialFeedbackParams); const [data, setData] = useState<FeedbackData | null>(null); const [orderNumber] = useState(initial.order); const [token] = useState(initial.token); const [answers, setAnswers] = useState<Record<string, number | string>>({}); const [comments, setComments] = useState(""); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState(false); const [busy, setBusy] = useState(true);
  useEffect(() => { window.setTimeout(() => { if (!initial.order || !initial.token) { setError("Use the secure feedback link connected to your order."); setBusy(false); return; } fetch(`/api/feedback?order=${encodeURIComponent(initial.order)}&token=${encodeURIComponent(initial.token)}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); if (body.alreadySubmitted) setSubmitted(true); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Feedback link is unavailable.")).finally(() => setBusy(false)); }, 0); }, [initial]);
  const submit = async () => { setError(""); setBusy(true); try { const response = await fetch("/api/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderNumber, token, answers, writtenFeedback: comments }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSubmitted(true); if (data) setData({ ...data, googleReviewUrl: body.googleReviewUrl }); void fetch("/api/analytics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ eventName: "feedback_submitted", context: { rating: answers.overall } }) }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Feedback could not be saved."); } finally { setBusy(false); } };
  return <div className="utility-page"><Header /><main className="utility-content"><div className="utility-title"><p className="eyebrow dark" style={{ justifyContent: "center" }}><span /> Straight to the Pizza 62 team</p><h1>How did we do?</h1><p>Your feedback helps us make the next order even better.</p></div>{busy && !data ? <div className="lookup-card" role="status">Opening your secure feedback form…</div> : error && !data ? <div className="lookup-card form-error" role="alert">{error}</div> : submitted ? <section className="feedback-card" style={{ textAlign: "center" }}><div className="confirmation-check">✓</div><h2 style={{ fontFamily: "Georgia, serif", fontSize: 38 }}>Thanks for telling us.</h2><p style={{ color: "var(--muted)", fontFamily: "Georgia, serif" }}>Your feedback is saved for the Pizza 62 team.</p><div className="review-cta"><h3>Share your experience on Google</h3><p>Every customer receives the same review invitation, whatever their rating.</p>{data?.googleReviewUrl ? <a href={data.googleReviewUrl} target="_blank" rel="noreferrer" onClick={() => void fetch("/api/analytics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ eventName: "google_review_clicked" }) })}>Leave a Google review ↗</a> : <p><strong>The owner is still configuring the direct review link.</strong></p>}</div><a className="text-button" href="/">Back to Pizza 62</a></section> : data ? <section className="feedback-card"><p className="eyebrow dark"><span /> Order {data.order.orderNumber}</p>{data.questions.filter((question) => question.type === "rating").map((question) => <div className="feedback-question" key={question.id}><h3>{question.label}{question.required ? " *" : ""}</h3><div className="rating-row" role="radiogroup" aria-label={question.label}>{Array.from({ length: question.ratingScale ?? 5 }, (_, index) => index + 1).map((rating) => <button type="button" role="radio" aria-checked={answers[question.id] === rating} className={answers[question.id] === rating ? "active" : ""} key={rating} onClick={() => setAnswers((current) => ({ ...current, [question.id]: rating }))}>{rating}</button>)}</div></div>)}<label style={{ marginTop: 20 }}>Written feedback<textarea rows={6} maxLength={2000} value={comments} onChange={(event) => setComments(event.target.value)} placeholder="Tell us what stood out—or what we can improve." /></label>{error ? <div className="form-error" role="alert">{error}</div> : null}<button className="primary-button" disabled={busy || !answers.overall} onClick={submit}>{busy ? "Saving…" : "Send feedback"}</button><p style={{ fontSize: 9, color: "var(--muted)", textAlign: "center" }}>Ratings of 1 or 2 create an immediate owner alert in the notification queue.</p></section> : null}</main></div>;
}
